Repository hackclub/pixeldust, pull requests merged in 2025-04, with the labels that each got.

#9 Adding Submission F1_Flags
  submissions/F1_Flags/BOM.md
  submissions/F1_Flags/Firmware/sketch.ino
  submissions/F1_Flags/README.md
  submissions/F1_Flags/gerbers.zip
  submissions/F1_Flags/pixeldust.kicad_pcb
  submissions/F1_Flags/pixeldust.kicad_pro
  submissions/F1_Flags/pixeldust.kicad_sch
Labels: ready-to-merge

#14 Add Pixel Matrix
  submissions/Pixel_Matrix/README.md
  submissions/Pixel_Matrix/bom pixel led.csv
  submissions/Pixel_Matrix/production/CPL pixel_led.csv
  submissions/Pixel_Matrix/production/Pixel_LED.zip
  submissions/Pixel_Matrix/production/main.c
  submissions/Pixel_Matrix/schematic.pdf
  submissions/Pixel_Matrix/src/Pixle LED.kicad_pcb
  submissions/Pixel_Matrix/src/Pixle LED.kicad_pro
  submissions/Pixel_Matrix/src/Pixle LED.kicad_sch
Labels: ready-to-merge

#17 Add the NeoPOV
  submissions/NeoPOV/README.md
  submissions/NeoPOV/production/BOM-pixeldust.csv
  submissions/NeoPOV/production/CPL-pixeldust.csv
  submissions/NeoPOV/production/GERBER-pixeldust.zip
  submissions/NeoPOV/production/main.c
  submissions/NeoPOV/schematic.pdf
  submissions/NeoPOV/src/pixeldust.kicad_pcb
  submissions/NeoPOV/src/pixeldust.kicad_pro
  submissions/NeoPOV/src/pixeldust.kicad_sch
  submissions/NeoPOV/{566FA67D-B490-4449-B369-A54D38CB7EF1}.png
  submissions/NeoPOV/{75C9A6B5-FC55-4164-96CC-F29968B07BFC}.png
  submissions/NeoPOV/{79DABEB5-1B74-45D2-BA26-4BB7B8300EDF}.png
  submissions/NeoPOV/{9351B20C-7F85-40AA-90F5-169E4E2700F6}.png
  submissions/NeoPOV/{AAC0A094-3DC6-4319-8320-21E18ACEDDB4}.png
  submissions/NeoPOV/{DFA667C8-EDB1-440C-8622-9CA37CFA46D8}.png
Labels: ready-to-merge

#20 Add LightRay
  submissions/LightRay/BOM.csv
  submissions/LightRay/README.md
  submissions/LightRay/pix/pcb.png
  submissions/LightRay/pix/pcb_renderbottom.png
  submissions/LightRay/pix/pcb_rendertop.png
  submissions/LightRay/pix/schematic.png
  submissions/LightRay/production/LightRay-gerbers.zip
  submissions/LightRay/production/main.ino
  submissions/LightRay/schematic.pdf
  submissions/LightRay/src/pixeldust.kicad_pcb
  submissions/LightRay/src/pixeldust.kicad_pro
  submissions/LightRay/src/pixeldust.kicad_sch
Labels: ready-to-merge

#22 Advay's pixeldust project
  submissions/pixeldust_submission/PixeldustBOM - Sheet1.csv
  submissions/pixeldust_submission/README.md
  submissions/pixeldust_submission/pixeldust_schematicPDF.pdf
  submissions/pixeldust_submission/production/gerbers.zip
  submissions/pixeldust_submission/production/pixeldust.py
  submissions/pixeldust_submission/src/pixeldustPCB.kicad_pcb
  submissions/pixeldust_submission/src/pixeldustPCB.kicad_pro
  submissions/pixeldust_submission/src/pixeldust_sch.kicad_sch
Labels: ready-to-merge

#27 boom
  submissions/boombox/README.md
  submissions/boombox/image-1.png
  submissions/boombox/image-2.png
  submissions/boombox/image-3.png
  submissions/boombox/image-4.png
  submissions/boombox/image-5.png
  submissions/boombox/image-6.png
  submissions/boombox/image.png
  submissions/boombox/main.c
  submissions/boombox/production/gerbers.zip
  submissions/boombox/schematic.pdf
  submissions/boombox/src/flashpro.kicad_pcb
  submissions/boombox/src/flashpro.kicad_pro
  submissions/boombox/src/flashpro.kicad_sch
Labels: ready-to-merge

#28 Lightbox
  submissions/3XAY_Lightbox/Pictures/LightBoxDesign.jpg
  submissions/3XAY_Lightbox/Pictures/LightBoxWiring.jpg
  submissions/3XAY_Lightbox/Pictures/PCBBack.jpg
  submissions/3XAY_Lightbox/Pictures/PCBFront.jpg
  submissions/3XAY_Lightbox/Pictures/Schematic.jpg
  submissions/3XAY_Lightbox/README.md
  submissions/3XAY_Lightbox/production/CPL-lightbox.csv
  submissions/3XAY_Lightbox/production/GERBER-lightbox.zip
  submissions/3XAY_Lightbox/production/main.py
  submissions/3XAY_Lightbox/src/lightbox.kicad_pcb
  submissions/3XAY_Lightbox/src/lightbox.kicad_pro
  submissions/3XAY_Lightbox/src/lightbox.kicad_sch
  submissions/README.md
Labels: ready-to-merge

#29 add: @turtureanu's LED glasses
  submissions/led-glasses/BOM-pixeldust-tutorial.csv
  submissions/led-glasses/README.md
  submissions/led-glasses/image-1.png
  submissions/led-glasses/image-2.png
  submissions/led-glasses/image-3.png
  submissions/led-glasses/image.png
  submissions/led-glasses/production/GERBER-pixeldust-tutorial.zip
  submissions/led-glasses/production/main.ino
  submissions/led-glasses/production/panelized-led-glasses-positions.csv
  submissions/led-glasses/schematic.pdf
  submissions/led-glasses/src/kicad/3d-models/SK6812MINI-012.wrl
  submissions/led-glasses/src/kicad/3d-models/SW_Push.wrl
  submissions/led-glasses/src/kicad/3d-models/XIAO-ESP32S3 v2.step
  submissions/led-glasses/src/kicad/fp-info-cache
  submissions/led-glasses/src/kicad/fp-lib-table
  submissions/led-glasses/src/kicad/kikit-panel.kikit_pnl
  submissions/led-glasses/src/kicad/led-glasses.kicad_sym
  submissions/led-glasses/src/kicad/libraries/footprints/led-glasses-custom.pretty/Capacitor_C1206_SMD.kicad_mod
  submissions/led-glasses/src/kicad/libraries/footprints/led-glasses-custom.pretty/LED-SMD_4P-L3.7-W3.5-P1.75-BR-SK6812MINI.kicad_mod
  submissions/led-glasses/src/kicad/libraries/footprints/led-glasses-custom.pretty/SW-SMD_L3.9-W3.0-P4.45.kicad_mod
  submissions/led-glasses/src/kicad/libraries/footprints/led-glasses-custom.pretty/XIAO-ESP32S3-SMD.kicad_mod
  submissions/led-glasses/src/kicad/panelized-led-glasses.kicad_dru
  submissions/led-glasses/src/kicad/panelized-led-glasses.kicad_pcb
  submissions/led-glasses/src/kicad/panelized-led-glasses.kicad_prl
  submissions/led-glasses/src/kicad/panelized-led-glasses.kicad_pro
  submissions/led-glasses/src/kicad/panelized-led-glasses.kicad_sch
  submissions/led-glasses/src/kicad/panelized-leds.kicad_sch
  submissions/led-glasses/src/kicad/sym-lib-table
  submissions/led-glasses/src/wokwi/main.ino
Labels: ready-to-merge

#30 My PixelPad
  submissions/duykhanh09103_PixelPad/BOM-pixeldust.csv
  submissions/duykhanh09103_PixelPad/images/pcb_back.png
  submissions/duykhanh09103_PixelPad/images/pcb_front.png
  submissions/duykhanh09103_PixelPad/images/schematic.png
  submissions/duykhanh09103_PixelPad/production/BOM-pixeldust.csv
  submissions/duykhanh09103_PixelPad/production/CPL-pixeldust.csv
  submissions/duykhanh09103_PixelPad/production/GERBER-pixeldust.zip
  submissions/duykhanh09103_PixelPad/readme.md
  submissions/duykhanh09103_PixelPad/schematic.pdf
  submissions/duykhanh09103_PixelPad/src/boot.ino
  submissions/duykhanh09103_PixelPad/src/pixeldust.kicad_pcb
  submissions/duykhanh09103_PixelPad/src/pixeldust.kicad_pro
  submissions/duykhanh09103_PixelPad/src/pixeldust.kicad_sch
Labels: ready-to-merge

#32 Add Mish's NeoPixel Themometer
  submissions/NeoPixel thermometer/BOM_NeoPixel_Thermometer.csv
  submissions/NeoPixel thermometer/README.md
  submissions/NeoPixel thermometer/images/2d-render-bottom.png
  submissions/NeoPixel thermometer/images/2d-render.png
  submissions/NeoPixel thermometer/images/3d-render-1.png
  submissions/NeoPixel thermometer/images/mockup.png
  submissions/NeoPixel thermometer/images/pcb-design.png
  submissions/NeoPixel thermometer/images/schematic.png
  submissions/NeoPixel thermometer/production/Gerber_NeoPixel_thermometer_PCB_2025-04-13.zip
  submissions/NeoPixel thermometer/schematic.pdf
  submissions/NeoPixel thermometer/src/FOOTPRINT/0d497d67f9394fd7803bab07a34ae998.efoo
  submissions/NeoPixel thermometer/src/FOOTPRINT/2e4e45d6d6334f86a54ba3d294a35c41.efoo
  submissions/NeoPixel thermometer/src/FOOTPRINT/3297c20b0e3f4d21bdb114583363f215.efoo
  submissions/NeoPixel thermometer/src/FOOTPRINT/35d1270423414f0cba553f26d6531d9e.efoo
  submissions/NeoPixel thermometer/src/FOOTPRINT/4410d0642e894373b16315e3e2052d55.efoo
  submissions/NeoPixel thermometer/src/FOOTPRINT/8d201673b1c348229ae8b467b756819d.efoo
  submissions/NeoPixel thermometer/src/FOOTPRINT/a7013e334f2349f38fb76896af0ffd62.efoo
  submissions/NeoPixel thermometer/src/FOOTPRINT/b571b959354e4b5fa0e25f07b7ed1544.efoo
  submissions/NeoPixel thermometer/src/FOOTPRINT/c01f6a417c6843fd867ec37846e72ae0.efoo
  submissions/NeoPixel thermometer/src/FOOTPRINT/c9d553f30c97489d84681c9b628c8e7e.efoo
  submissions/NeoPixel thermometer/src/FOOTPRINT/d0a1b04d98eb4ed29ab4f0a7c4bbdf3c.efoo
  submissions/NeoPixel thermometer/src/FOOTPRINT/d4ac3562d3d54b9fa483a409c2da5972.efoo
  submissions/NeoPixel thermometer/src/FOOTPRINT/e4bd26bb180f4c7b8660cf92393b1a18.efoo
  submissions/NeoPixel thermometer/src/FOOTPRINT/eebaed25b5c54f8ba5873b7f3b09bc62.efoo
  submissions/NeoPixel thermometer/src/PCB/9404f6c488be40a982f87036262754e6.epcb
  submissions/NeoPixel thermometer/src/SHEET/dc245426aae14eb9a685622f271fe03a/1.esch
  submissions/NeoPixel thermometer/src/SYMBOL/0fe1aac4a0254de7831cc8aa8fc129d8.esym
  submissions/NeoPixel thermometer/src/SYMBOL/1bf421b5f12445cabbabc73d2c7984bc.esym
  submissions/NeoPixel thermometer/src/SYMBOL/20b40b05bc1f49438887157c627926fc.esym
  submissions/NeoPixel thermometer/src/SYMBOL/2a2f92abd56f4f8da0524bb79acdbbe4.esym
  submissions/NeoPixel thermometer/src/SYMBOL/314143c3624b45709e1ce501da97b379.esym
  submissions/NeoPixel thermometer/src/SYMBOL/521a4a4628cf4c88a4459b76a7857267.esym
  submissions/NeoPixel thermometer/src/SYMBOL/558c350fd02f4a028ab8f60c9ee56397.esym
  submissions/NeoPixel thermometer/src/SYMBOL/5bc7fa1a21614b4b8e3e3e566eac9fa4.esym
  submissions/NeoPixel thermometer/src/SYMBOL/5c67ba5299ef46fe89ad3d335537f64c.esym
  submissions/NeoPixel thermometer/src/SYMBOL/6736e6d4ba774222be9eefb2d77630ac.esym
  submissions/NeoPixel thermometer/src/SYMBOL/6b17c75ad6f6499f9375e2988080b325.esym
  submissions/NeoPixel thermometer/src/SYMBOL/9931535efb4f4ed3b51362d161d1fb09.esym
  submissions/NeoPixel thermometer/src/SYMBOL/a9f15ca341a54d96b4678afac48da26e.esym
  submissions/NeoPixel thermometer/src/SYMBOL/b159fa7910364bcdb0a257412d0fb68b.esym
  submissions/NeoPixel thermometer/src/SYMBOL/bcc04021dc9c4138bbe6a44cfaa72981.esym
  submissions/NeoPixel thermometer/src/SYMBOL/bec75a463fe945689255eb49ec81ec96.esym
  submissions/NeoPixel thermometer/src/SYMBOL/bf765d0846984046b3ff7a26d4a2fc7d.esym
  submissions/NeoPixel thermometer/src/SYMBOL/cbfe3f3bd42c496f84b0cdd5c4a637a5.esym
  submissions/NeoPixel thermometer/src/SYMBOL/ce55c6b65c1340fab2ddb31d3d3651ef.esym
  submissions/NeoPixel thermometer/src/SYMBOL/d849cb68a3ac415e8a7b5229e419d72c.esym
  submissions/NeoPixel thermometer/src/SYMBOL/df0d9fc92d3d4385978211009e5d282b.esym
  submissions/NeoPixel thermometer/src/project.json
Labels: ready-to-merge

#33 Add Sheikah Eye
  submissions/shiekah-eye/BOM-sheikah.csv
  submissions/shiekah-eye/README.md
  submissions/shiekah-eye/pictures/sheikah_3d.png
  submissions/shiekah-eye/pictures/sheikah_schematic.png
  submissions/shiekah-eye/pictures/shiekah_pcb.png
  submissions/shiekah-eye/production/main.c
  submissions/shiekah-eye/production/shiekah-gerber.zip
  submissions/shiekah-eye/src/sheikah-eye.kicad_pcb
  submissions/shiekah-eye/src/sheikah-eye.kicad_prl
  submissions/shiekah-eye/src/sheikah-eye.kicad_pro
  submissions/shiekah-eye/src/sheikah-eye.kicad_sch
Labels: ready-to-merge

#34 Add GIF_Matrix
  submissions/Gif_Matrix/BOM-GIF_Matrix.csv
  submissions/Gif_Matrix/README.md
  submissions/Gif_Matrix/assets/pcb.png
  submissions/Gif_Matrix/assets/pcb3d.png
  submissions/Gif_Matrix/assets/schematic.png
  submissions/Gif_Matrix/production/GERBER-GIF_Matrix.zip
  submissions/Gif_Matrix/production/main.py
  submissions/Gif_Matrix/schematic.pdf
  submissions/Gif_Matrix/src/GIF_Matrix.kicad_pcb
  submissions/Gif_Matrix/src/GIF_Matrix.kicad_pro
  submissions/Gif_Matrix/src/GIF_Matrix.kicad_sch
Labels: ready-to-merge

#35 DynamicWhiteHat's Project
  submissions/OctoGlow/BOM_Documentation.pdf
  submissions/OctoGlow/Production/gerber.zip
  submissions/OctoGlow/Production/main.c
  submissions/OctoGlow/README.md
  submissions/OctoGlow/SuperPixel.csv
  submissions/OctoGlow/image-1.png
  submissions/OctoGlow/image-2.png
  submissions/OctoGlow/image.png
  submissions/OctoGlow/src/SuperPixel.kicad_pcb
  submissions/OctoGlow/src/SuperPixel.kicad_pro
  submissions/OctoGlow/src/SuperPixel.kicad_sch
Labels: ready-to-merge

#39 Add Pixel-Dongle -- Person20020
  submissions/pixel-dongle/.gitignore
  submissions/pixel-dongle/README.md
  submissions/pixel-dongle/pixel-dongle.pdf
  submissions/pixel-dongle/src/pixel-dongle.py
  submissions/pixel-dongle/src/pixel-dongle/pixel-dongle.kicad_pcb
  submissions/pixel-dongle/src/pixel-dongle/pixel-dongle.kicad_prl
  submissions/pixel-dongle/src/pixel-dongle/pixel-dongle.kicad_pro
  submissions/pixel-dongle/src/pixel-dongle/pixel-dongle.kicad_sch
  submissions/pixel-dongle/src/pixel-dongle/pixel-dongle.kicad_sch-bak
  submissions/pixel-dongle/src/pixel-dongle/~pixel-dongle.kicad_pcb.lck
  submissions/pixel-dongle/src/pixel-dongle/~pixel-dongle.kicad_sch.lck
Labels: ready-to-merge

#40 ZeBoard
  submissions/ZeDisplay/BOM-pixeldust-zeboard.csv
  submissions/ZeDisplay/README.md
  submissions/ZeDisplay/image-1.png
  submissions/ZeDisplay/image.png
  submissions/ZeDisplay/production/GERBER-pixeldust-zeboard.zip
  submissions/ZeDisplay/production/main.py
  submissions/ZeDisplay/schematic_zeboard.pdf
  submissions/ZeDisplay/src/ledboard.kicad_pcb
  submissions/ZeDisplay/src/ledboard.kicad_pro
  submissions/ZeDisplay/src/ledboard.kicad_sch
Labels: ready-to-merge

#42 Add weather-ring
  submissions/weather-ring/BOM-WeatherRing.csv
  submissions/weather-ring/PDF-WeatherRing.pdf
  submissions/weather-ring/README.md
  submissions/weather-ring/images/kicad_cOEeU4dHsN.png
  submissions/weather-ring/images/kicad_mnjKRoxERJ.png
  submissions/weather-ring/images/msedge_1bTsaRlqID.gif
  submissions/weather-ring/images/msedge_Eh1RorWQkV.gif
  submissions/weather-ring/images/msedge_XAOi5b5xcQ.gif
  submissions/weather-ring/images/msedge_u0dh2ssR2J.gif
  submissions/weather-ring/production/GERBERS-weather-ring.zip
  submissions/weather-ring/production/main.py
  submissions/weather-ring/production/rotary.py
  submissions/weather-ring/production/rotary_irq_esp.py
  submissions/weather-ring/src/WeatherRing.kicad_pcb
  submissions/weather-ring/src/WeatherRing.kicad_prl
  submissions/weather-ring/src/WeatherRing.kicad_pro
  submissions/weather-ring/src/WeatherRing.kicad_sch
Labels: ready-to-merge

#45 Add Submission canis_led
  submissions/canis_led/3D.png
  submissions/canis_led/BOM-canis_pixeldust.csv
  submissions/canis_led/PCB.png
  submissions/canis_led/README.md
  submissions/canis_led/production/Canis_GERBER.zip
  submissions/canis_led/production/sketch.ino
  submissions/canis_led/schematic.pdf
  submissions/canis_led/src/canis_pixeldust.kicad_pcb
  submissions/canis_led/src/canis_pixeldust.kicad_pro
  submissions/canis_led/src/canis_pixeldust.kicad_sch
Labels: ready-to-merge

#48 Shard
  main.py
  submissions/Shard/README.md
  submissions/Shard/pcb.png
  submissions/Shard/production/bom.csv
  submissions/Shard/production/designators.csv
  submissions/Shard/production/netlist.ipc
  submissions/Shard/production/positions.csv
  submissions/Shard/production/shard.zip
  submissions/Shard/sch.png
  submissions/Shard/src/shard.kicad_pcb
  submissions/Shard/src/shard.kicad_prl
  submissions/Shard/src/shard.kicad_pro
  submissions/Shard/src/shard.kicad_sch
Labels: ready-to-merge

#5 Add TheJSMatrix
  submisssions/TheJSMatrix/BOM.csv
  submisssions/TheJSMatrix/PCB.png
  submisssions/TheJSMatrix/README.md
  submisssions/TheJSMatrix/production/TheJSMatrix-all-pos.csv
  submisssions/TheJSMatrix/production/gerbers.zip
  submisssions/TheJSMatrix/production/main.py
  submisssions/TheJSMatrix/schem.png
  submisssions/TheJSMatrix/src/TheJSMatrix.kicad_pcb
  submisssions/TheJSMatrix/src/TheJSMatrix.kicad_pro
  submisssions/TheJSMatrix/src/TheJSMatrix.kicad_sch
Labels: error

#6 Added Submission: ProximityGradient
  submissions/ProximityGradient/HRO_TYPE-C-31-M-12.step
  submissions/ProximityGradient/ProximityGradient-backups/ProximityGradient-2025-04-07_134701.zip
  submissions/ProximityGradient/ProximityGradient-backups/ProximityGradient-2025-04-07_235001.zip
  submissions/ProximityGradient/ProximityGradient-backups/ProximityGradient-2025-04-17_091644.zip
  submissions/ProximityGradient/ProximityGradient-backups/ProximityGradient-2025-04-17_190812.zip
  submissions/ProximityGradient/ProximityGradient.kicad_pcb
  submissions/ProximityGradient/ProximityGradient.kicad_prl
  submissions/ProximityGradient/ProximityGradient.kicad_pro
  submissions/ProximityGradient/ProximityGradient.kicad_sch
  submissions/ProximityGradient/README.md
  submissions/ProximityGradient/Seeed Studio XIAO RP2040 v26.step
  submissions/ProximityGradient/code/hcsr04.py
  submissions/ProximityGradient/code/main.py
  submissions/ProximityGradient/fp-info-cache
  submissions/ProximityGradient/fp-lib-table
  submissions/ProximityGradient/sym-lib-table
Labels: missing code file

#21 Add Lightbulb
  submissions/lightbulb/README.md
  submissions/lightbulb/bom.csv
  submissions/lightbulb/production/gerbers_lightbulb.zip
  submissions/lightbulb/production/main.c
  submissions/lightbulb/schematic.pdf
  submissions/lightbulb/src/lightbulb.kicad_pcb
  submissions/lightbulb/src/lightbulb.kicad_pro
  submissions/lightbulb/src/lightbulb.kicad_sch
Labels: ready-to-merge, missing code file
